### ISSUE TITLE
pserve fails to start

### ISSUE THREAD

**Issue by alanorth** [ilri/data.ilri.org-app#1]
On Linux with virtualenv set up, requirements installed, and `setup.py` successfully ran... pserve fails:

``` console
(datailriorg) [aorth@noma: ~/src/git/data.ilri.org-app]$ pserve ./development.ini         
Traceback (most recent call last):
  File "/home/aorth/.pyenv/versions/datailriorg/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.5.7', 'console_scripts', 'pserve')()
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/aorth/src/git/data.ilri.org-app/datailriorgapp/__init__.py", line 22, in main
    config.scan()
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/pyramid/config/__init__.py", line 930, in scan
    ignore=ignore)
  File "/home/aorth/.pyenv/versions/datailriorg/lib64/python3.4/site-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/home/aorth/src/git/data.ilri.org-app/datailriorgapp/views.py", line 2, in <module>
    from resources import basicCSS
ImportError: No module named 'resources'
```

**Comment by qlands** [comment]
Humm... I cannot reproduce the bug in my distro... Shall I pop in to check it out?

**Comment by alanorth** [comment]
Hmm, I'm at Java House right now and I just set this up on my Mac and it works. Python 2.7.9 in the virtualenv. I'll have to check my virtualenv on Linux when I get back to the office.

**Comment by alanorth** [comment]
I figured it out. It's a problem with Python 3. My virtualenv was using 3.4.x. So this works:

``` console
$ pyenv virtualenv 2.7.9 datailriorg
$ pyenv activate datailriorg
$ pip install -r requirements.txt
...
```

I'll add a note to the build instructions that mentions the Python version required.
